version: '3'
services:
  builder:
    container_name: builder
    image: amazoncorretto:17
    volumes:
      - .:/opt/build
      - app_home:/opt/app
    working_dir: /opt/build
    command: "./gradlew copyDeps -x test"

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mattaeng
      MYSQL_USER: mattaeng
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    platform: linux/x86_64
    restart: always

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_started
    volumes:
      - app_home:/opt/app
    environment:
      TZ: Asia/Seoul
    ports:
      - "8081:8080"
    restart: always

volumes:
  app_home:
  mysql_data:
