spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:p6spy:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/dog?authSource=admin
#    redis:
#      host: localhost
#      port: 6379

decorator:
  datasource:
    p6spy:
      enable-logging: false

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}