spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mattaeng
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create
    show-sql: true

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
